# Linear Regression practice
Linear regression practice using the car price prediction problem.

In [1]:
import pandas as pd
import numpy as np
import wget

In [6]:
# Only run this piece of code for fresh save of the dataset
url = 'https://raw.githubusercontent.com/anjanavasudevan/mlbookcamp-code/master/chapter-02-car-price/data.csv'
file = wget.download(url)


## Data Preparation and analysis

In [2]:
#importing the data

#df = pd.read_csv(file)
df = pd.read_csv('data.csv')
df.head(10)

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   
5  BMW    1 Series  2012  premium unleaded (required)      230.0   
6  BMW    1 Series  2012  premium unleaded (required)      300.0   
7  BMW    1 Series  2012  premium unleaded (required)      300.0   
8  BMW    1 Series  2012  premium unleaded (required)      230.0   
9  BMW    1 Series  2013  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   
5               6.0            MANUAL  rear wheel drive              2.0   
6               6.0            MANUAL  rear wheel drive              2.0   
7               6.0            MANUAL  rear wheel drive              2.0   
8               6.0            MANUAL  rear wheel drive              2.0   
9               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   
5                     Luxury,Performance      Compact         Coupe   
6                     Luxury,Performance      Compact   Convertible   
7                Luxury,High-Performance      Compact         Coupe   
8                                 Luxury      Compact   Convertible   
9                                 Luxury      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500  
5           28        18        3916  31200  
6           26        17        3916  44100  
7           28        20        3916  39300  
8           28        18        3916  36900  
9           27        18        3916  37200

## String Processing

Clean the string for easy labelling

In [3]:
# Checking the types of data in the file
df.dtypes

Make                  object
Model                 object
Year                   int64
Engine Fuel Type      object
Engine HP            float64
Engine Cylinders     float64
Transmission Type     object
Driven_Wheels         object
Number of Doors      float64
Market Category       object
Vehicle Size          object
Vehicle Style         object
highway MPG            int64
city mpg               int64
Popularity             int64
MSRP                   int64
dtype: object

In [4]:
# Changing names of columns to ones without space - easy access
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ', '_')
df.columns

Index(['make', 'model', 'year', 'engine_fuel_type', 'engine_hp',
       'engine_cylinders', 'transmission_type', 'driven_wheels',
       'number_of_doors', 'market_category', 'vehicle_size', 'vehicle_style',
       'highway_mpg', 'city_mpg', 'popularity', 'msrp'],
      dtype='object')

In [5]:
# Replacing all spaces in string objects to underscores
columns_with_string = list(df.dtypes[df.dtypes == 'object'].index)

for column in columns_with_string:
    df[column] = df[column].str.lower().str.replace(' ', '_')

df.tail(10)



make   model  year                engine_fuel_type  engine_hp  \
11904      bmw      z8  2002     premium_unleaded_(required)      394.0   
11905      bmw      z8  2003     premium_unleaded_(required)      394.0   
11906    acura     zdx  2011     premium_unleaded_(required)      300.0   
11907    acura     zdx  2011     premium_unleaded_(required)      300.0   
11908    acura     zdx  2011     premium_unleaded_(required)      300.0   
11909    acura     zdx  2012     premium_unleaded_(required)      300.0   
11910    acura     zdx  2012     premium_unleaded_(required)      300.0   
11911    acura     zdx  2012     premium_unleaded_(required)      300.0   
11912    acura     zdx  2013  premium_unleaded_(recommended)      300.0   
11913  lincoln  zephyr  2006                regular_unleaded      221.0   

       engine_cylinders transmission_type      driven_wheels  number_of_doors  \
11904               8.0            manual   rear_wheel_drive              2.0   
11905               8.0            manual   rear_wheel_drive              2.0   
11906               6.0         automatic    all_wheel_drive              4.0   
11907               6.0         automatic    all_wheel_drive              4.0   
11908               6.0         automatic    all_wheel_drive              4.0   
11909               6.0         automatic    all_wheel_drive              4.0   
11910               6.0         automatic    all_wheel_drive              4.0   
11911               6.0         automatic    all_wheel_drive              4.0   
11912               6.0         automatic    all_wheel_drive              4.0   
11913               6.0         automatic  front_wheel_drive              4.0   

                      market_category vehicle_size  vehicle_style  \
11904  exotic,luxury,high-performance      compact    convertible   
11905  exotic,luxury,high-performance      compact    convertible   
11906      crossover,hatchback,luxury      midsize  4dr_hatchback   
11907      crossover,hatchback,luxury      midsize  4dr_hatchback   
11908      crossover,hatchback,luxury      midsize  4dr_hatchback   
11909      crossover,hatchback,luxury      midsize  4dr_hatchback   
11910      crossover,hatchback,luxury      midsize  4dr_hatchback   
11911      crossover,hatchback,luxury      midsize  4dr_hatchback   
11912      crossover,hatchback,luxury      midsize  4dr_hatchback   
11913                          luxury      midsize          sedan   

       highway_mpg  city_mpg  popularity    msrp  
11904           19        12        3916  130000  
11905           19        12        3916  131500  
11906           23        16         204   46020  
11907           23        16         204   56570  
11908           23        16         204   50520  
11909           23        16         204   46120  
11910           23        16         204   56670  
11911           23        16         204   50620  
11912           23        16         204   50920  
11913           26        17          61   28995

In [6]:
# Information on the numeric data
df.describe()

year    engine_hp  engine_cylinders  number_of_doors  \
count  11914.000000  11845.00000      11884.000000     11908.000000   
mean    2010.384338    249.38607          5.628829         3.436093   
std        7.579740    109.19187          1.780559         0.881315   
min     1990.000000     55.00000          0.000000         2.000000   
25%     2007.000000    170.00000          4.000000         2.000000   
50%     2015.000000    227.00000          6.000000         4.000000   
75%     2016.000000    300.00000          6.000000         4.000000   
max     2017.000000   1001.00000         16.000000         4.000000   

        highway_mpg      city_mpg    popularity          msrp  
count  11914.000000  11914.000000  11914.000000  1.191400e+04  
mean      26.637485     19.733255   1554.911197  4.059474e+04  
std        8.863001      8.987798   1441.855347  6.010910e+04  
min       12.000000      7.000000      2.000000  2.000000e+03  
25%       22.000000     16.000000    549.000000  2.100000e+04  
50%       26.000000     18.000000   1385.000000  2.999500e+04  
75%       30.000000     22.000000   2009.000000  4.223125e+04  
max      354.000000    137.000000   5657.000000  2.065902e+06

## Checking the unique values and visualise data

In [9]:
for column in df.columns:
    print("{}:".format(column))
    print(df[column].unique()[:5])
    print(df[column].nunique())

make:
['bmw' 'audi' 'fiat' 'mercedes-benz' 'chrysler']
48
model:
['1_series_m' '1_series' '100' '124_spider' '190-class']
914
year:
[2011 2012 2013 1992 1993]
28
engine_fuel_type:
['premium_unleaded_(required)' 'regular_unleaded'
 'premium_unleaded_(recommended)' 'flex-fuel_(unleaded/e85)' 'diesel']
10
engine_hp:
[335. 300. 230. 320. 172.]
356
engine_cylinders:
[ 6.  4.  5.  8. 12.]
9
transmission_type:
['manual' 'automatic' 'automated_manual' 'direct_drive' 'unknown']
5
driven_wheels:
['rear_wheel_drive' 'front_wheel_drive' 'all_wheel_drive'
 'four_wheel_drive']
4
number_of_doors:
[ 2.  4.  3. nan]
3
market_category:
['factory_tuner,luxury,high-performance' 'luxury,performance'
 'luxury,high-performance' 'luxury' 'performance']
71
vehicle_size:
['compact' 'midsize' 'large']
3
vehicle_style:
['coupe' 'convertible' 'sedan' 'wagon' '4dr_hatchback']
16
highway_mpg:
[26 28 27 25 24]
59
city_mpg:
[19 20 18 17 16]
69
popularity:
[3916 3105  819  617 1013]
48
msrp:
[46135 40650 36350 29450 34

## Clean up missing values

If there are missing values, fit the missing values using one of the following techniques:
1. Forward fill - take values from the data ahead
2. Backward fill - take values from data behind
3. Average fill - fill the values using the mean
4. Zero fill - Pad the `NaN` using zeroes

In [7]:
# Information on not null values:
numeric_columns = list(df.dtypes[df.dtypes != 'object'].index)

#print(df[df.make.isnull()].head())
for column in numeric_columns:
    print("{}".format(column))
    print(df[df[column].isnull()].head())
    print("\n")


year
Empty DataFrame
Columns: [make, model, year, engine_fuel_type, engine_hp, engine_cylinders, transmission_type, driven_wheels, number_of_doors, market_category, vehicle_size, vehicle_style, highway_mpg, city_mpg, popularity, msrp]
Index: []


engine_hp
         make        model  year                engine_fuel_type  engine_hp  \
539      fiat         500e  2015                        electric        NaN   
540      fiat         500e  2016                        electric        NaN   
541      fiat         500e  2017                        electric        NaN   
2905  lincoln  continental  2017  premium_unleaded_(recommended)        NaN   
2906  lincoln  continental  2017  premium_unleaded_(recommended)        NaN   

      engine_cylinders transmission_type      driven_wheels  number_of_doors  \
539                0.0      direct_drive  front_wheel_drive              2.0   
540                0.0      direct_drive  front_wheel_drive              2.0   
541                0.0      

In [22]:
# Only the engine_hp column has Nans. 
df.loc[df.make == 'fiat']

make       model  year                engine_fuel_type  engine_hp  \
32   fiat  124_spider  2017  premium_unleaded_(recommended)      160.0   
33   fiat  124_spider  2017  premium_unleaded_(recommended)      160.0   
34   fiat  124_spider  2017  premium_unleaded_(recommended)      160.0   
539  fiat        500e  2015                        electric        NaN   
540  fiat        500e  2016                        electric        NaN   
..    ...         ...   ...                             ...        ...   
593  fiat        500x  2017                regular_unleaded      180.0   
594  fiat        500x  2017                regular_unleaded      180.0   
595  fiat        500x  2017                regular_unleaded      180.0   
596  fiat        500x  2017                regular_unleaded      180.0   
597  fiat        500x  2017  premium_unleaded_(recommended)      160.0   

     engine_cylinders transmission_type      driven_wheels  number_of_doors  \
32                4.0            manual   rear_wheel_drive              2.0   
33                4.0            manual   rear_wheel_drive              2.0   
34                4.0            manual   rear_wheel_drive              2.0   
539               0.0      direct_drive  front_wheel_drive              2.0   
540               0.0      direct_drive  front_wheel_drive              2.0   
..                ...               ...                ...              ...   
593               4.0         automatic  front_wheel_drive              4.0   
594               4.0         automatic    all_wheel_drive              4.0   
595               4.0         automatic    all_wheel_drive              4.0   
596               4.0         automatic  front_wheel_drive              4.0   
597               4.0            manual  front_wheel_drive              4.0   

    market_category vehicle_size  vehicle_style  highway_mpg  city_mpg  \
32      performance      compact    convertible           35        26   
33      performance      compact    convertible           35        26   
34      performance      compact    convertible           35        26   
539       hatchback      compact  2dr_hatchback          108       122   
540       hatchback      compact  2dr_hatchback          103       121   
..              ...          ...            ...          ...       ...   
593       crossover      compact        4dr_suv           30        22   
594       crossover      compact        4dr_suv           29        21   
595       crossover      compact        4dr_suv           29        21   
596       crossover      compact        4dr_suv           30        22   
597       crossover      compact        4dr_suv           33        25   

     popularity   msrp  
32          819  27495  
33          819  24995  
34          819  28195  
539         819  31800  
540         819  31800  
..          ...    ...  
593         819  25135  
594         819  25235  
595         819  23890  
596         819  23335  
597         819  19995  

[62 rows x 16 columns]