# Linear Regression practice
Linear regression practice using the car price prediction problem.

In [81]:
import pandas as pd
import numpy as np
import wget

# Plotting options

import plotly.graph_objs as go
import plotly.offline as py


In [82]:
# Only run this piece of code for fresh save of the dataset
#url = 'https://raw.githubusercontent.com/anjanavasudevan/mlbookcamp-code/master/chapter-02-car-price/data.csv'
#file = wget.download(url)


## Data Preparation and analysis

In [83]:
#importing the data

#df = pd.read_csv(file)
df = pd.read_csv('data.csv')
df.head(10)

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   
5  BMW    1 Series  2012  premium unleaded (required)      230.0   
6  BMW    1 Series  2012  premium unleaded (required)      300.0   
7  BMW    1 Series  2012  premium unleaded (required)      300.0   
8  BMW    1 Series  2012  premium unleaded (required)      230.0   
9  BMW    1 Series  2013  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   
5               6.0            MANUAL  rear wheel drive              2.0   
6               6.0            MANUAL  rear wheel drive              2.0   
7               6.0            MANUAL  rear wheel drive              2.0   
8               6.0            MANUAL  rear wheel drive              2.0   
9               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   
5                     Luxury,Performance      Compact         Coupe   
6                     Luxury,Performance      Compact   Convertible   
7                Luxury,High-Performance      Compact         Coupe   
8                                 Luxury      Compact   Convertible   
9                                 Luxury      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500  
5           28        18        3916  31200  
6           26        17        3916  44100  
7           28        20        3916  39300  
8           28        18        3916  36900  
9           27        18        3916  37200

## String Processing

Clean the string for easy labelling

In [84]:
# Checking the types of data in the file
df.dtypes

Make                  object
Model                 object
Year                   int64
Engine Fuel Type      object
Engine HP            float64
Engine Cylinders     float64
Transmission Type     object
Driven_Wheels         object
Number of Doors      float64
Market Category       object
Vehicle Size          object
Vehicle Style         object
highway MPG            int64
city mpg               int64
Popularity             int64
MSRP                   int64
dtype: object

In [85]:
# Changing names of columns to ones without space - easy access
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ', '_')
df.columns

Index(['make', 'model', 'year', 'engine_fuel_type', 'engine_hp',
       'engine_cylinders', 'transmission_type', 'driven_wheels',
       'number_of_doors', 'market_category', 'vehicle_size', 'vehicle_style',
       'highway_mpg', 'city_mpg', 'popularity', 'msrp'],
      dtype='object')

In [86]:
# Replacing all spaces in string objects to underscores
columns_with_string = list(df.dtypes[df.dtypes == 'object'].index)

for column in columns_with_string:
    df[column] = df[column].str.lower().str.replace(' ', '_')

df.tail(10)



make   model  year                engine_fuel_type  engine_hp  \
11904      bmw      z8  2002     premium_unleaded_(required)      394.0   
11905      bmw      z8  2003     premium_unleaded_(required)      394.0   
11906    acura     zdx  2011     premium_unleaded_(required)      300.0   
11907    acura     zdx  2011     premium_unleaded_(required)      300.0   
11908    acura     zdx  2011     premium_unleaded_(required)      300.0   
11909    acura     zdx  2012     premium_unleaded_(required)      300.0   
11910    acura     zdx  2012     premium_unleaded_(required)      300.0   
11911    acura     zdx  2012     premium_unleaded_(required)      300.0   
11912    acura     zdx  2013  premium_unleaded_(recommended)      300.0   
11913  lincoln  zephyr  2006                regular_unleaded      221.0   

       engine_cylinders transmission_type      driven_wheels  number_of_doors  \
11904               8.0            manual   rear_wheel_drive              2.0   
11905               8.0            manual   rear_wheel_drive              2.0   
11906               6.0         automatic    all_wheel_drive              4.0   
11907               6.0         automatic    all_wheel_drive              4.0   
11908               6.0         automatic    all_wheel_drive              4.0   
11909               6.0         automatic    all_wheel_drive              4.0   
11910               6.0         automatic    all_wheel_drive              4.0   
11911               6.0         automatic    all_wheel_drive              4.0   
11912               6.0         automatic    all_wheel_drive              4.0   
11913               6.0         automatic  front_wheel_drive              4.0   

                      market_category vehicle_size  vehicle_style  \
11904  exotic,luxury,high-performance      compact    convertible   
11905  exotic,luxury,high-performance      compact    convertible   
11906      crossover,hatchback,luxury      midsize  4dr_hatchback   
11907      crossover,hatchback,luxury      midsize  4dr_hatchback   
11908      crossover,hatchback,luxury      midsize  4dr_hatchback   
11909      crossover,hatchback,luxury      midsize  4dr_hatchback   
11910      crossover,hatchback,luxury      midsize  4dr_hatchback   
11911      crossover,hatchback,luxury      midsize  4dr_hatchback   
11912      crossover,hatchback,luxury      midsize  4dr_hatchback   
11913                          luxury      midsize          sedan   

       highway_mpg  city_mpg  popularity    msrp  
11904           19        12        3916  130000  
11905           19        12        3916  131500  
11906           23        16         204   46020  
11907           23        16         204   56570  
11908           23        16         204   50520  
11909           23        16         204   46120  
11910           23        16         204   56670  
11911           23        16         204   50620  
11912           23        16         204   50920  
11913           26        17          61   28995

In [87]:
# Information on the numeric data
df.describe()

year    engine_hp  engine_cylinders  number_of_doors  \
count  11914.000000  11845.00000      11884.000000     11908.000000   
mean    2010.384338    249.38607          5.628829         3.436093   
std        7.579740    109.19187          1.780559         0.881315   
min     1990.000000     55.00000          0.000000         2.000000   
25%     2007.000000    170.00000          4.000000         2.000000   
50%     2015.000000    227.00000          6.000000         4.000000   
75%     2016.000000    300.00000          6.000000         4.000000   
max     2017.000000   1001.00000         16.000000         4.000000   

        highway_mpg      city_mpg    popularity          msrp  
count  11914.000000  11914.000000  11914.000000  1.191400e+04  
mean      26.637485     19.733255   1554.911197  4.059474e+04  
std        8.863001      8.987798   1441.855347  6.010910e+04  
min       12.000000      7.000000      2.000000  2.000000e+03  
25%       22.000000     16.000000    549.000000  2.100000e+04  
50%       26.000000     18.000000   1385.000000  2.999500e+04  
75%       30.000000     22.000000   2009.000000  4.223125e+04  
max      354.000000    137.000000   5657.000000  2.065902e+06

## Checking the unique values and visualise data

In [88]:
for column in df.columns:
    print("{}:".format(column))
    print(df[column].unique()[:5])
    print(df[column].nunique())

make:
['bmw' 'audi' 'fiat' 'mercedes-benz' 'chrysler']
48
model:
['1_series_m' '1_series' '100' '124_spider' '190-class']
914
year:
[2011 2012 2013 1992 1993]
28
engine_fuel_type:
['premium_unleaded_(required)' 'regular_unleaded'
 'premium_unleaded_(recommended)' 'flex-fuel_(unleaded/e85)' 'diesel']
10
engine_hp:
[335. 300. 230. 320. 172.]
356
engine_cylinders:
[ 6.  4.  5.  8. 12.]
9
transmission_type:
['manual' 'automatic' 'automated_manual' 'direct_drive' 'unknown']
5
driven_wheels:
['rear_wheel_drive' 'front_wheel_drive' 'all_wheel_drive'
 'four_wheel_drive']
4
number_of_doors:
[ 2.  4.  3. nan]
3
market_category:
['factory_tuner,luxury,high-performance' 'luxury,performance'
 'luxury,high-performance' 'luxury' 'performance']
71
vehicle_size:
['compact' 'midsize' 'large']
3
vehicle_style:
['coupe' 'convertible' 'sedan' 'wagon' '4dr_hatchback']
16
highway_mpg:
[26 28 27 25 24]
59
city_mpg:
[19 20 18 17 16]
69
popularity:
[3916 3105  819  617 1013]
48
msrp:
[46135 40650 36350 29450 34

## Visualising the price

In [89]:
#plotting
pd.options.plotting.backend = "plotly"

In [90]:
# Viewing the range of prices of the cars
#ply.iplot(go.Histogram(x=df['msrp']))
fig = go.Figure(go.Histogram(x=df['msrp'],
                           name='Vehicle'))

fig.update_layout(title='Vehicle prices',
                  showlegend=True)

fig.show()


In [91]:
# Interactive Plot environment
data = [go.Histogram(x=df['msrp'],
                           name='Vehicle')]
layout = go.Layout(title = 'Vehicle Prices', xaxis_title = 'MSRP')

figure = go.Figure(data=data, layout=layout)
py.iplot(figure)


In [92]:
# Viewing things on log scale
log_val = df['msrp'].apply(np.log10)

# Plot the log values
data = [go.Histogram(x=log_val,
                    name='Vehicle')]
layout = go.Layout(title='Vehicle Prices (in log scale)', xaxis_title='log(MSRP)')

figure = go.Figure(data=data, layout=layout)
py.iplot(figure)


In [93]:
# Information on null values
df.isnull().sum()

make                    0
model                   0
year                    0
engine_fuel_type        3
engine_hp              69
engine_cylinders       30
transmission_type       0
driven_wheels           0
number_of_doors         6
market_category      3742
vehicle_size            0
vehicle_style           0
highway_mpg             0
city_mpg                0
popularity              0
msrp                    0
dtype: int64

## Splitting the dataset

The dataset is split in the following manner:
1. 60% -  training
2. 20% - Validation
3. 20% - Testing

The ratios can change according to preference, but a certain portion of the dataset must be allocated for validation and testing

In [94]:
# Setting the ratios
n = int(len(df))

n_val = int(0.2*n)
n_test = n_val
n_train = n - (n_val + n_test)

print('Length of dataset: {}\nLength of training set: {}\nLength of validation set: {}\nLength of testing set:{}'.format
                (n, n_train, n_val, n_test))

# Check to see if the split tallies
print(n == n_val+n_test+n_train)


Length of dataset: 11914
Length of training set: 7150
Length of validation set: 2382
Length of testing set:2382
True


In [95]:
# Shuffling the dataset and split accordingly - Can use scikit's train-test-split module
idx = np.arange(n)

# Fixing the seed for ensuring same randomness
np.random.seed(11)
np.random.shuffle(idx)

idx

array([ 8428, 11661,  4001, ...,  5200,  3775, 10137])

In [96]:
# Split the dataset
df_train = df.iloc[idx[:n_train]]
df_val = df.iloc[idx[n_train:(n_train+n_val)]]
df_test = df.iloc[idx[(n_train+n_val):]]

df_train.head(10)

make              model  year                engine_fuel_type  \
8428        acura                rdx  2016  premium_unleaded_(recommended)   
11661      suzuki               xl-7  2004                regular_unleaded   
4001          gmc           envoy_xl  2006                regular_unleaded   
2904      lincoln        continental  2017                regular_unleaded   
11722      suzuki                xl7  2009                regular_unleaded   
308        nissan               370z  2015     premium_unleaded_(required)   
3553   land_rover           defender  1997                regular_unleaded   
3187     cadillac                ct6  2017     premium_unleaded_(required)   
5197      pontiac                 g6  2009                regular_unleaded   
11115       volvo  v60_cross_country  2015                regular_unleaded   

       engine_hp  engine_cylinders transmission_type      driven_wheels  \
8428       279.0               6.0         automatic  front_wheel_drive   
11661      185.0               6.0            manual   four_wheel_drive   
4001       291.0               6.0         automatic   rear_wheel_drive   
2904       305.0               6.0         automatic    all_wheel_drive   
11722      252.0               6.0         automatic    all_wheel_drive   
308        332.0               6.0            manual   rear_wheel_drive   
3553       182.0               8.0         automatic   four_wheel_drive   
3187       404.0               6.0         automatic    all_wheel_drive   
5197       221.0               6.0         automatic  front_wheel_drive   
11115      250.0               5.0         automatic    all_wheel_drive   

       number_of_doors          market_category vehicle_size    vehicle_style  \
8428               4.0         crossover,luxury      midsize          4dr_suv   
11661              4.0                      NaN      midsize          4dr_suv   
4001               4.0                      NaN        large          4dr_suv   
2904               4.0                   luxury        large            sedan   
11722              4.0                crossover      midsize          4dr_suv   
308                2.0         high-performance      compact      convertible   
3553               2.0                   luxury      compact  convertible_suv   
3187               4.0  luxury,high-performance        large            sedan   
5197               2.0              performance      midsize            coupe   
11115              4.0         crossover,luxury      midsize            wagon   

       highway_mpg  city_mpg  popularity   msrp  
8428            29        20         204  40370  
11661           20        15         481  21999  
4001            19        14         549  27380  
2904            24        16          61  49515  
11722           23        16         481  29079  
308             24        17        2009  48100  
3553            14        12         258  36931  
3187            26        18        1624  87495  
5197            26        17         210  24080  
11115           28        20         870  41000

In [97]:
# Reset the index numbers
def reset_indexing(dataframe):
    return dataframe.reset_index(drop=True)


df_train = reset_indexing(df_train)
df_val = reset_indexing(df_val)
df_test = reset_indexing(df_test)

In [98]:
# Pulling out the output columns
y_train = np.log10(df_train['msrp'].values)
y_val = np.log10(df_val['msrp'].values)
y_test = np.log10(df_test['msrp'].values)

# Deleting the output columns
del df_train['msrp']
del df_val['msrp']
del df_test['msrp']

df_train.head(10)


make              model  year                engine_fuel_type  \
0       acura                rdx  2016  premium_unleaded_(recommended)   
1      suzuki               xl-7  2004                regular_unleaded   
2         gmc           envoy_xl  2006                regular_unleaded   
3     lincoln        continental  2017                regular_unleaded   
4      suzuki                xl7  2009                regular_unleaded   
5      nissan               370z  2015     premium_unleaded_(required)   
6  land_rover           defender  1997                regular_unleaded   
7    cadillac                ct6  2017     premium_unleaded_(required)   
8     pontiac                 g6  2009                regular_unleaded   
9       volvo  v60_cross_country  2015                regular_unleaded   

   engine_hp  engine_cylinders transmission_type      driven_wheels  \
0      279.0               6.0         automatic  front_wheel_drive   
1      185.0               6.0            manual   four_wheel_drive   
2      291.0               6.0         automatic   rear_wheel_drive   
3      305.0               6.0         automatic    all_wheel_drive   
4      252.0               6.0         automatic    all_wheel_drive   
5      332.0               6.0            manual   rear_wheel_drive   
6      182.0               8.0         automatic   four_wheel_drive   
7      404.0               6.0         automatic    all_wheel_drive   
8      221.0               6.0         automatic  front_wheel_drive   
9      250.0               5.0         automatic    all_wheel_drive   

   number_of_doors          market_category vehicle_size    vehicle_style  \
0              4.0         crossover,luxury      midsize          4dr_suv   
1              4.0                      NaN      midsize          4dr_suv   
2              4.0                      NaN        large          4dr_suv   
3              4.0                   luxury        large            sedan   
4              4.0                crossover      midsize          4dr_suv   
5              2.0         high-performance      compact      convertible   
6              2.0                   luxury      compact  convertible_suv   
7              4.0  luxury,high-performance        large            sedan   
8              2.0              performance      midsize            coupe   
9              4.0         crossover,luxury      midsize            wagon   

   highway_mpg  city_mpg  popularity  
0           29        20         204  
1           20        15         481  
2           19        14         549  
3           24        16          61  
4           23        16         481  
5           24        17        2009  
6           14        12         258  
7           26        18        1624  
8           26        17         210  
9           28        20         870

In [107]:
np.shape(y_train)

(7150,)

## Linear Regression

Model the price using all the numeric columns. A sample Linear regression model is given below:

3-dimensional model for the $i$th observation, given by:
$$
\hat{y_i} = \hat{\beta_0} + \hat{\beta_1}x_{i1} + \hat{\beta_2}x_{i2} + \hat{\beta_3}x_{i3}
$$

In [101]:
# Preparing the baseline model
df_train.dtypes

make                  object
model                 object
year                   int64
engine_fuel_type      object
engine_hp            float64
engine_cylinders     float64
transmission_type     object
driven_wheels         object
number_of_doors      float64
market_category       object
vehicle_size          object
vehicle_style         object
highway_mpg            int64
city_mpg               int64
popularity             int64
dtype: object

In [102]:
# Extracting the numeric columns only
x_train_columns = ['engine_hp', 'engine_cylinders', 'highway_mpg', 'city_mpg', 'popularity']
# x_train = df_train[x_train_columns].values

## Clean up missing values

If there are missing values, fit the missing values using one of the following techniques:
1. Forward fill - take values from the data ahead
2. Backward fill - take values from data behind
3. Average fill - fill the values using the mean
4. Zero fill - Pad the `NaN` using zeroes

## Clean up missing values

If there are missing values, fit the missing values using one of the following techniques:
1. Forward fill - take values from the data ahead
2. Backward fill - take values from data behind
3. Average fill - fill the values using the mean
4. Zero fill - Pad the `NaN` using zeroes

In [103]:
# Fill the missing values using zero fill
df_train.isnull().sum()

make                    0
model                   0
year                    0
engine_fuel_type        1
engine_hp              45
engine_cylinders       17
transmission_type       0
driven_wheels           0
number_of_doors         5
market_category      2255
vehicle_size            0
vehicle_style           0
highway_mpg             0
city_mpg                0
popularity              0
dtype: int64

In [110]:
# Fill values
x_train = df_train[x_train_columns].fillna(0).values
np.shape(x_train)

(7150, 5)

In [111]:
# Stacking ones for extra beta
x_train = np.column_stack([np.ones(x_train.shape[0]), x_train])
np.shape(x_train)

(7150, 6)

In [113]:
# Actual linear regression - rough version, will be codified as function
XTX = x_train.T.dot(x_train)
XTX_inv = np.linalg.inv(XTX)
ß = XTX_inv.dot(x_train.T).dot(y_train)
ß


array([ 3.42883246e+00,  4.22037749e-03, -6.75993161e-02,  6.99635917e-03,
        5.75798631e-03, -3.50492009e-06])

In [119]:
## Comparison between actual and predicted values

y_hat = x_train.dot(ß)

## Plotting set up
trace1 = go.Histogram(x = y_train, name = 'Actual values')
trace2 = go.Histogram(x = y_hat, name='Prediction')

data = [trace1, trace2]

layout = go.Layout(title='Vehicle Prices - actual vs predicted (in log scale)',
                   xaxis_title='log(MSRP)')

figure = go.Figure(data=data, layout=layout)
py.iplot(figure)

